## Data

In machine learning, statistics and other applications, we need to represent data.  

Often we represent data in _vectors_ which are just ordered lists of numbers or words.  

For instance if we have data about people, which records their _height (cm)_, _weight (kg)_, and _sex_, data about a particular person might be represented as a vector like this one:

```
[173.101, 70.5,'M']
```
This vector says that the person in question is 173.101 cm tall, weighs 70.5 kg, and is a male.  

If we have data about several people, then we have many vectors of information.  Typically these are stacked to form a _matrix_.

For instance if we have three people, Alice, Bob, and Carol, then their data might together make a 3 by 3 matrix like this one:

```
[
[150.701, 62.5,'F'],
[173.101, 70.5,'M'],
[140.19, 51.5,'F']
]
```
I have written this as a list of lists.


In [47]:
# Review of enumeration.....

L = list("ABC")
L
for letter in L:
    print(letter)
for index,letter in enumerate(L):
    print(index,letter)

A
B
C
0 A
1 B
2 C


In [4]:
#height #weight #sex
data = [
[150.701, 62.5,'F'],  #alice
[173.101, 70.5,'M'],  #bob
[140.19, 51.5,'F']    #carol
]

data[1][0]
data[2][0] #Carol's height
data[0][2] #Alice's sex


for i,name in enumerate(["alice","bob","carol"]):
    for j,propertyx in enumerate(["height","weight","sex"]):
        print("{}'s {} is {}".format(name,propertyx,data[i][j]))

alice's height is 150.701
alice's weight is 62.5
alice's sex is F
bob's height is 173.101
bob's weight is 70.5
bob's sex is M
carol's height is 140.19
carol's weight is 51.5
carol's sex is F


## Lists of lists

Sometimes lists of lists are called 2-dimensional arrays.  

Every element in a 2D array can be specified by its row and column.

For instance Bob's sex is in the second row and , third column of the matrix `data`.





In [2]:
## Accessing Bob's sex

data[1][2]

'M'

Notice that we first specify the row `data[1]`.  So `data[1]` is itself a list.  Then we get the third column by accessing the third element of that list:

```
data[1][2]
```


## Numpy arrays

Numpy (numerical python) supports $n$-dimensional arrays.

They call these `ndarray` [types](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.html).  

We will only use 1-dimensional and 2-dimensional arrays.  

Let's first go over some ways to generate 1-dimensional arrays of numbers in numpy.

We'll discuss

1. conversion from python arrays
1. arange
1. linspace
1. logspace
1. zeros
1. ones
1. random


In [1]:
# Conversion from python arrays...

import numpy as np

L = [1,2,3,4,5]

Lnp = np.array(L)

Lnp

array([1, 2, 3, 4, 5])

In [4]:
# Unlike a python array, in a numpy array all elements are the same type
# If any string is included, then everything must be a string

L = [1,2,3,4,5,'a']


Lnp = np.array(L)

Lnp,Lnp.dtype

(array(['1', '2', '3', '4', '5', 'a'], dtype='<U21'), dtype('<U21'))

In [5]:
# arange

# This method gives you an "interval" of values.
# You specify a start, a stop, and a step

np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [6]:
# linspace

# This is similar to arange, but you give a start, a stop, and the _number_ of points.

np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [16]:
# logspace

# Similar to linspace, but now the points are separated by geometrically increasing amounts.
# There is an implicit base b (10 by default)
# It starts at b**start and stops at b**stop

np.logspace(1,5,num=10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [37]:
# zeros

# Often you just want an array of zeros.

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:

# Or an array of ones

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:

#  Here are 10 values sampled from a standard normal distribution

np.random.randn(10)

array([ 1.07942322,  0.3080182 ,  1.39840618,  1.4107934 ,  0.48400112,
       -0.70532046, -1.22057276,  0.26371531, -0.60847375,  2.35205058])

In [49]:
#  Here are 5 integers sampled uniformly at random between 0 and 10

np.random.randint(0,10,5)

array([9, 8, 1, 8, 6])

### Numpy 2-D arrays

The way to create a 2-D array in numpy is usually to reshape a 1-D array. 

Below are examples of using the reshape command.


In [35]:
A = np.linspace(0,1,16)
A

array([0.        , 0.06666667, 0.13333333, 0.2       , 0.26666667,
       0.33333333, 0.4       , 0.46666667, 0.53333333, 0.6       ,
       0.66666667, 0.73333333, 0.8       , 0.86666667, 0.93333333,
       1.        ])

In [36]:
A.reshape(4,4)

array([[0.        , 0.06666667, 0.13333333, 0.2       ],
       [0.26666667, 0.33333333, 0.4       , 0.46666667],
       [0.53333333, 0.6       , 0.66666667, 0.73333333],
       [0.8       , 0.86666667, 0.93333333, 1.        ]])

In [39]:
A.reshape(2,8)

array([[0.        , 0.06666667, 0.13333333, 0.2       , 0.26666667,
        0.33333333, 0.4       , 0.46666667],
       [0.53333333, 0.6       , 0.66666667, 0.73333333, 0.8       ,
        0.86666667, 0.93333333, 1.        ]])

In [40]:
A.reshape(8,2)

array([[0.        , 0.06666667],
       [0.13333333, 0.2       ],
       [0.26666667, 0.33333333],
       [0.4       , 0.46666667],
       [0.53333333, 0.6       ],
       [0.66666667, 0.73333333],
       [0.8       , 0.86666667],
       [0.93333333, 1.        ]])

#### Linear algebra operations

Often we want to do matrix arithmetic on numpy arrays.  
By default when you "multiply" numpy arrays you don't get the matrix product, you get respective elements multiplied together.



In [2]:
import numpy as np

A = np.random.randint(0,10,9).reshape(3,3)
B = np.random.randint(0,10,9).reshape(3,3)
A

array([[6, 6, 7],
       [0, 6, 3],
       [5, 2, 2]])

In [55]:
B

array([[6, 1, 7],
       [2, 3, 2],
       [2, 0, 9]])

In [56]:
A*B

array([[42,  1, 49],
       [ 0, 27, 18],
       [ 8,  0, 18]])

### Matrix product

If you want to get the matrix product then you have two options.

One is to conver to the numpy "matrix" type.


In [57]:
Am = np.matrix(A)
Bm = np.matrix(B)
Am*Bm

matrix([[ 58,  10, 114],
        [ 36,  27,  99],
        [ 28,   4,  46]])

Another method is to use the "dot" method.

This is uglier, but I recommend it, because slices of "matrix" types can be weird (see "slicing" below).


In [58]:
A.dot(B)

array([[ 58,  10, 114],
       [ 36,  27,  99],
       [ 28,   4,  46]])

#### Other matrix operations

Often we want the inverse, the transpose, or the "pseudo-inverse".

Here is how to get each of these.


In [62]:
#The inverse 

np.linalg.inv(A)


array([[-0.2       ,  0.02222222,  0.6       ],
       [-0.4       ,  0.15555556,  0.7       ],
       [ 0.4       , -0.04444444, -0.7       ]])

In [63]:
# Everything is numerical, so it can be a little sloppy.
# Here's A*A^(-1)
A.dot(np.linalg.inv(A))

array([[ 1.00000000e+00, -2.08166817e-17, -3.33066907e-16],
       [ 0.00000000e+00,  1.00000000e+00,  3.33066907e-16],
       [ 2.22044605e-16, -2.77555756e-17,  1.00000000e+00]])

In [64]:
# The transpose

A.T

array([[7, 0, 4],
       [1, 9, 0],
       [7, 9, 2]])

In [65]:
#  The pseudo-inverse
#  (we'll explain this later)
# For a square matrix, the pseudo-inverse is just the inverse

np.linalg.pinv(A)

array([[-0.2       ,  0.02222222,  0.6       ],
       [-0.4       ,  0.15555556,  0.7       ],
       [ 0.4       , -0.04444444, -0.7       ]])

In [66]:
#  But for rectangular matrices the pseudo-inverse is also defined (where the regular inverse is not)

C = np.random.randn(16).reshape(8,2)
C

array([[-1.67395215, -0.75074329],
       [-1.61175077,  2.33154874],
       [-1.99531934,  2.06477457],
       [-0.16325107,  2.59638869],
       [ 0.19130273,  1.42616082],
       [-1.11099185,  0.19262457],
       [ 0.05995189,  0.48841386],
       [-0.89279144, -0.76279689]])

In [67]:
np.linalg.pinv(C)

array([[-0.20113761, -0.09224429, -0.14147895,  0.0690268 ,  0.06749242,
        -0.11055328,  0.02252836, -0.11930847],
       [-0.10117965,  0.0880915 ,  0.05915257,  0.15227336,  0.09297126,
        -0.02519059,  0.03165492, -0.07597376]])

## Slicing

Now we practice doing 2D array slicing.

You may want to review 1D array slicing if you're still not sure how that works.

https://stackoverflow.com/questions/509211/understanding-pythons-slice-notation

The basic form of a 2D slice is 

```
A[<slice of rows>,<slice of columns>]
```

Here are some examples.


In [5]:
import numpy as np
A = np.array(data)
A

array([['150.701', '62.5', 'F'],
       ['173.101', '70.5', 'M'],
       ['140.19', '51.5', 'F']], dtype='<U32')

In [6]:
# Numpy arrays can be sliced multidimensionally, similarly to the way 1D Python

# All rows, third column
A[:,2]

array(['F', 'M', 'F'], dtype='<U32')

In [7]:
# All rows, all columns

A[:,:]

array([['150.701', '62.5', 'F'],
       ['173.101', '70.5', 'M'],
       ['140.19', '51.5', 'F']], dtype='<U32')

In [8]:
# Second row, all columns
A[1,:]

array(['173.101', '70.5', 'M'], dtype='<U32')

In [11]:
# Second row, columns 0,1
A[1,0:2]

array(['173.101', '70.5'], dtype='<U32')

In [14]:
#Exercise:

#  What is this?

A[0:2,1:]

array([['62.5', 'F'],
       ['70.5', 'M']], dtype='<U32')

In [12]:
A

array([['150.701', '62.5', 'F'],
       ['173.101', '70.5', 'M'],
       ['140.19', '51.5', 'F']], dtype='<U32')

In [38]:
sex_col = A[:,-1]
print(sex_col)
A[sex_col == 'F',:]

['F' 'M' 'F']


array([['150.701', '62.5', 'F'],
       ['140.19', '51.5', 'F']], dtype='<U32')

In [18]:
A = np.arange(1,17).reshape(4,4)
X = A[:,1].reshape(4,1)
X
Y = A[1:3,2:]
Y

array([[ 7,  8],
       [11, 12]])

In [73]:
#Exercise:

#A = np.array(data)


## Slice out these:

# 1)  The 3rd column

# 2)  The last row
# 3)  The last 2 columns


## The shape of an array

Here we look at how to make matrices out of 1D arrays, and to "flatten" 2D arrays into 1D arrays.


In [71]:
B = np.random.randn(25).reshape(5,5)
B

array([[ 0.82231058,  0.97975016,  0.42898614,  1.07242233, -1.00640184],
       [-1.04577882, -0.38708494,  1.97851304, -1.28083628,  1.48228689],
       [ 0.37813029,  0.30997016, -0.50344834,  1.83635373,  0.68876621],
       [-0.12174403,  1.46998238, -0.4915397 ,  1.12176541, -0.76528718],
       [-1.30419748,  1.19987133,  2.14436563,  1.17276708, -0.11806334]])

In [72]:
B.flatten()

array([ 0.82231058,  0.97975016,  0.42898614,  1.07242233, -1.00640184,
       -1.04577882, -0.38708494,  1.97851304, -1.28083628,  1.48228689,
        0.37813029,  0.30997016, -0.50344834,  1.83635373,  0.68876621,
       -0.12174403,  1.46998238, -0.4915397 ,  1.12176541, -0.76528718,
       -1.30419748,  1.19987133,  2.14436563,  1.17276708, -0.11806334])

In [78]:
np.zeros(10).reshape(2,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [79]:
np.eye(5)  # The multiplicative identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [99]:
A = np.array( range(12))
A


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [85]:
A.shape

(12,)

In [86]:
A = A.reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
A.shape

(3, 4)

In [88]:
A.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [89]:
A.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [100]:
A = np.array( range(12))
C = A.reshape(4,3).T
C

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [74]:
#Exercise:

#  Create a 2D numpy array of dimensions 4x7


## Vectorization

Operations on numpy arrays are _vectorized_.  That means that most operations happen to all the elements at once.  
Here are some examples.



In [75]:
A = np.array(range(11))
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
A + 1 # + operator is overloaded to add 1 to each entry

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
A*1/2 # so is the multiplication operator

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [78]:
A > 4 # so is > operator

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [79]:
A**3 - 14*A**2+np.sqrt(A)-10

array([ -10.        ,  -22.        ,  -56.58578644, -107.26794919,
       -168.        , -232.76393202, -295.55051026, -350.35424869,
       -391.17157288, -412.        , -406.83772234])

In [47]:
B = np.ones(len(A))
B

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [48]:
B+A

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [50]:
# This is the dot product, from linear algebra.

B.dot(A) == sum(B*A)

True

In [39]:
# This is item-wise multiplication

B*A

array([ 0,  9, 16, 21, 24, 25, 24, 21, 16,  9,  0])

In [81]:
# Numpy has some built-in vectorized functions like sine, cosine, exp, log, etc.

np.sin(A) + np.cos(A)


array([ 1.        ,  1.38177329,  0.49315059, -0.84887249, -1.41044612,
       -0.67526209,  0.68075479,  1.41088885,  0.84385821, -0.49901178,
       -1.38309264])

In [41]:
np.exp(A)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [59]:
number_of_numbers = 70
np.linspace(start,stop,number_of_numbers)

array([0.        , 0.02898551, 0.05797101, 0.08695652, 0.11594203,
       0.14492754, 0.17391304, 0.20289855, 0.23188406, 0.26086957,
       0.28985507, 0.31884058, 0.34782609, 0.37681159, 0.4057971 ,
       0.43478261, 0.46376812, 0.49275362, 0.52173913, 0.55072464,
       0.57971014, 0.60869565, 0.63768116, 0.66666667, 0.69565217,
       0.72463768, 0.75362319, 0.7826087 , 0.8115942 , 0.84057971,
       0.86956522, 0.89855072, 0.92753623, 0.95652174, 0.98550725,
       1.01449275, 1.04347826, 1.07246377, 1.10144928, 1.13043478,
       1.15942029, 1.1884058 , 1.2173913 , 1.24637681, 1.27536232,
       1.30434783, 1.33333333, 1.36231884, 1.39130435, 1.42028986,
       1.44927536, 1.47826087, 1.50724638, 1.53623188, 1.56521739,
       1.5942029 , 1.62318841, 1.65217391, 1.68115942, 1.71014493,
       1.73913043, 1.76811594, 1.79710145, 1.82608696, 1.85507246,
       1.88405797, 1.91304348, 1.94202899, 1.97101449, 2.        ])

In [57]:
start  = 0
stop = 2
increment = 0.01
x = np.arange(start,stop,increment)
x

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09,
       1.1 , 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 ,
       1.21, 1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31,
       1.32, 1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42,
       1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.

In [8]:
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(-1,1,0.01)
y = 8*x**2-2*x
plt.plot(x,np.sin(x))
plt.plot(x,y)
plt.legend(["sin","quadratic"])
plt.title("Sine vs a quadratic")
plt.show()

# Exercise:

In the same window, plot all of the following

    1. y = sin(x)
    2. y = x
    3. y = x - x**3/(3*2)
    4. y = x - x**3/3 + x**5/(5*4*3*2)
    5. y = x - x**3/3 + x**5/(5*4*3*2) - x**7/(7*6*5*4*3*2)


In [10]:
import matplotlib.pyplot as plt
import numpy as np
N = 4
x = np.arange(-3,3,0.01)
y = np.sin(x)
y2 = x
y3 = x - x**3/(3*2)
y4 = x - x**3/3 + x**5/(5*4*3*2)
y5 = x - x**3/3 + x**5/(5*4*3*2) - x**7/(7*6*5*4*3*2)
plt.plot(x,y)
plt.plot(x,y2)
plt.plot(x,y3)
plt.plot(x,y4)
plt.plot(x,y5)
plt.legend(['sin','one','two','three','four','five'])
plt.show()

In [20]:
import math
plt.plot(x,np.sin(x))
N = 10
y = np.zeros(len(x))
for i in range(N):
    y += (-1)**(i)*x**(2*i+1)/math.factorial(2*i+1)
    plt.plot(x,y)
plt.show()    

In [68]:
import matplotlib.pyplot as plt

x = np.arange(-1,1,0.001)

leg = []
for i in range(1,6):
    plt.plot(x,1/i*x**2)
    leg.append(r"$1/{}x^2$".format(i))
plt.legend(leg)    
plt.show()

In [69]:
np.log(np.e)==1


True

In [17]:
#one way to do subplots

import matplotlib.pyplot as plt
import numpy as np

fig,axes = plt.subplots(nrows=2,ncols=2, figsize=(7,7))
x = np.arange(-3,3,0.1)
axes[0,0].plot(x,x)
axes[0,1].plot(x,np.sin(x))
axes[1,0].plot(x,np.sin(2*x))
axes[1,1].plot(x,x**3)
plt.show()

In [19]:
np.diff(np.array([1,2,4,7]))


array([1, 2, 3])

In [79]:
#another way to do subplots

x = np.arange(-3,3,0.01)

plt.subplot(3,1,1)
plt.plot(x,x**2)


plt.subplot(3,1,2)
plt.plot(x,np.ones(len(x))*42,color="green")


plt.subplot(3,1,3)
plt.plot(x,np.tan(x),color="blue")
plt.show()

In [75]:
x = np.arange(0,2,0.01)
plt.subplot(2,2,1)
plt.plot(x,x**2)

plt.subplot(2,2,2)
plt.plot(x,np.sin(x**3),color="red")

plt.subplot(2,2,3)
plt.plot(x,x**4,color="purple")

plt.subplot(2,2,4)
plt.plot(x,x**5,color="orange")
plt.show()

In [73]:
import numpy as np
x = np.arange(0,2,0.01)

import matplotlib.pyplot as plt

y = np.log(x)
plt.plot(x,y)
y = np.sqrt(x)
plt.plot(x,y)
plt.legend([r"$\ln(x)$",r"$\sqrt{x}$"])
plt.title("The greatest functions of all time.")
plt.show()

/ext/anaconda5/lib/python3.6/site-packages/ipykernel/__main__.py:6: RuntimeWarning: divide by zero encountered in log


## Axes

What happens if you sum a numpy array?  Let's see...



In [16]:
A = np.array(range(16)).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
np.sum(A,axis=1)

array([ 6, 22, 38, 54])

Weirdly the sum is a vector?

If you check, you'll see that these are _column_ sums.  That means that 24 is the sum of the first column, 28 is the sum of the 2nd column, etc.

What if you want to sum the rows instead?

That's what the optional _axis_ parameter is for.

Columns are axis 0.  Rows are axis 1.


In [47]:
np.sum(A,axis=0)

array([24, 28, 32, 36])

In [50]:
np.sum(A,axis=1)

array([ 6, 22, 38, 54])

Not specifying an axis just adds up everything.


In [51]:
np.sum(A)

120

Lots of numpy built-in function work this way...

In [55]:
np.argmax(A,axis=0)

array([3, 3, 3, 3])

The above output means that the row index of the biggest element in each column is 3.

Analyzing a random matrix might shed more light on this...

In [20]:
B = np.array([ np.random.random() for i in range(12)]).reshape(3,4)
B

array([[0.79428538, 0.38188804, 0.66323077, 0.83878719],
       [0.69391367, 0.71631395, 0.98692463, 0.15381442],
       [0.97299405, 0.49236495, 0.53853741, 0.99318735]])

In [38]:
#Exercise
#Find the index (row and column) and the value of the biggest entry in B
np.argmax(B)
B.flatten()[11]

0.9931873525764595

In [26]:
maxes = np.argmax(B,axis=0)
maxes
B.T[[0,1,2,3],maxes]

array([0.97299405, 0.71631395, 0.98692463, 0.99318735])

In [41]:
np.median(B,axis=0)

array([0.79428538, 0.49236495, 0.66323077, 0.83878719])

In [62]:
np.argmax(B,axis=1)

array([3, 1, 0])

In [64]:
# Exercise:

# Find the argmin for B on both axes and interpret the result

# Do the same thing for the mean and median.


In [83]:
#  You can use argmin, argmax, and even "argsort"
nums = np.array([8,9,1,3,0,1,44])
nums[np.argsort(nums)]


array([ 0,  1,  1,  3,  8,  9, 44])

# And more...

Here is a nice tutorial showing you how to do more things...

[http://cs231n.github.io/python-numpy-tutorial/](http://cs231n.github.io/python-numpy-tutorial/)
    